"""TopoLab package."""

from topolab.api import create_app
from topolab.dataset import (
    DATASET_MANIFEST_VERSION,
    DATASET_SAMPLE_VERSION,
    SPLIT_CONTRACT_VERSION,
    DatasetEnvironment,
    DatasetManifest,
    DatasetSample,
    DatasetSplit,
    DatasetSplitCounts,
    assign_case_split,
)
from topolab.experiment import (
    CASE_ID_PREFIX,
    CASE_SCHEMA_VERSION,
    INPUT_CHANNEL_COUNT,
    INPUT_CHANNEL_NAMES,
    LABEL_GENERATOR_VERSION,
    PROJECTION_MAX_ITERATIONS,
    PROJECTION_VOLUME_TOLERANCE,
    SOLVER_CONTRACT_VERSION,
    EncodedCase,
    ExperimentCase,
    ProjectedDensity,
    build_case_id,
    canonical_case_json,
    encode_case,
    project_design_density,
)
from topolab.fem import (
    LinearStaticResult,
    assemble_global_stiffness,
    build_constrained_dofs,
    build_load_vector,
    hex8_element_stiffness,
    isotropic_elasticity_matrix,
    select_face_nodes,
    solve_linear_static,
)
from topolab.jobs import (
    RunCursorError,
    RunManager,
    RunNotFoundError,
    RunPage,
    RunSnapshot,
    RunStatus,
    RunSummary,
)
from topolab.label_artifacts import (
    LABEL_ARTIFACT_VERSION,
    LabelArtifactError,
    LabelArtifactReference,
    canonical_label_bytes,
    read_label_artifact,
    write_label_artifact,
)
from topolab.labels import (
    LABEL_COMPLIANCE_RELATIVE_TOLERANCE,
    LABEL_RECORD_VERSION,
    LABEL_VOLUME_TOLERANCE,
    LabelGenerationError,
    LabelRecord,
    generate_label,
)
from topolab.mesh import Hex8Mesh, generate_structured_hex8
from topolab.model import FaceLoad, FixedFaceSupport, PointLoad
from topolab.persistence import RunStore, SqliteRunStore, StoredRun
from topolab.problem import (
    FaceLoadDefinition,
    FixedFaceSupportDefinition,
    IterationResult,
    MaterialDefinition,
    MeshDefinition,
    OptimizationDefinition,
    PointLoadDefinition,
    TopologyProblem,
    TopologyResult,
    solve_problem,
)
from topolab.simp import (
    ComplianceResult,
    DensityFilter,
    OptimizationCancelledError,
    SimpConfig,
    SimpIteration,
    SimpResult,
    apply_density_filter,
    backpropagate_density_gradient,
    build_density_filter,
    evaluate_compliance,
    optimality_criteria_update,
    optimize_simp,
    simp_element_moduli,
)

__version__ = "0.3.0"

__all__ = [
    "CASE_ID_PREFIX",
    "CASE_SCHEMA_VERSION",
    "DATASET_MANIFEST_VERSION",
    "DATASET_SAMPLE_VERSION",
    "DatasetEnvironment",
    "DatasetManifest",
    "DatasetSample",
    "DatasetSplit",
    "DatasetSplitCounts",
    "EncodedCase",
    "ExperimentCase",
    "INPUT_CHANNEL_COUNT",
    "INPUT_CHANNEL_NAMES",
    "LABEL_GENERATOR_VERSION",
    "LABEL_ARTIFACT_VERSION",
    "LABEL_COMPLIANCE_RELATIVE_TOLERANCE",
    "LABEL_RECORD_VERSION",
    "LABEL_VOLUME_TOLERANCE",
    "LabelGenerationError",
    "LabelArtifactError",
    "LabelArtifactReference",
    "LabelRecord",
    "Hex8Mesh",
    "LinearStaticResult",
    "ComplianceResult",
    "DensityFilter",
    "FaceLoad",
    "FaceLoadDefinition",
    "FixedFaceSupport",
    "FixedFaceSupportDefinition",
    "PointLoad",
    "PointLoadDefinition",
    "ProjectedDensity",
    "PROJECTION_MAX_ITERATIONS",
    "PROJECTION_VOLUME_TOLERANCE",
    "IterationResult",
    "MaterialDefinition",
    "MeshDefinition",
    "OptimizationCancelledError",
    "OptimizationDefinition",
    "RunManager",
    "RunCursorError",
    "RunNotFoundError",
    "RunPage",
    "RunSnapshot",
    "RunStore",
    "RunStatus",
    "RunSummary",
    "SimpConfig",
    "SimpIteration",
    "SimpResult",
    "SPLIT_CONTRACT_VERSION",
    "SOLVER_CONTRACT_VERSION",
    "SqliteRunStore",
    "StoredRun",
    "TopologyProblem",
    "TopologyResult",
    "apply_density_filter",
    "assemble_global_stiffness",
    "assign_case_split",
    "build_constrained_dofs",
    "build_case_id",
    "build_load_vector",
    "backpropagate_density_gradient",
    "build_density_filter",
    "create_app",
    "canonical_case_json",
    "canonical_label_bytes",
    "evaluate_compliance",
    "encode_case",
    "generate_structured_hex8",
    "generate_label",
    "hex8_element_stiffness",
    "isotropic_elasticity_matrix",
    "optimality_criteria_update",
    "optimize_simp",
    "project_design_density",
    "read_label_artifact",
    "select_face_nodes",
    "simp_element_moduli",
    "solve_problem",
    "solve_linear_static",
    "write_label_artifact",
]
